### ISSUE TITLE
training function error

### ISSUE THREAD

**Issue by rajae-Bens** [Dhanachandra/bert-crf4NER#1]
Hi,

First, thank u for having shared ur code with us
I tried to apply ur code on my own data but I am getting this error 

![Screen Shot 2020-11-22 at 8 50 21 PM](https://user-images.githubusercontent.com/58187895/99915498-5be84580-2d04-11eb-8e9d-11f3788d82d3.png)

Can u help plz

Thank u

**Comment by Dhanachandra** [comment]
Make sure your dataset has the same format as https://github.com/synalp/NER
.


*--*


*With Regards,*
*Dhanachandra | Research Engineer*
*ezDI*
*Healthcare Data Intelligence*
*"Empowering people to deliver innovative solutions that enhance human
life."*

**Comment by rajae-Bens** [comment]
Yes it does and all the process before training is going very well
but as u see in the screen shot it stops when it starts the execution of the train function 
I think because the memory is exhausted  it may be due to the length of my data be
I tried to change the maxlen in the pad function but It gave me an error 
can u plz explain when to change the length of the data before feeding to BERT?

**Comment by Dhanachandra** [comment]
In Line number 113 make maxlen = 50 or whatever length of your choices.

**Comment by rajae-Bens** [comment]
First, thank s for the quick answer 

Yes as I said I ve already dit this I fixed maxlen to 128 but it gave me an error 

![Screen Shot 2020-11-23 at 8 38 43 AM](https://user-images.githubusercontent.com/58187895/99938094-67b92380-2d67-11eb-9446-d806f7229f53.png)

do u have any idea plz?
thank u

**Comment by Dhanachandra** [comment]
Please change the line number 114 as below
do_pad = lambda x, seqlen: [sample[x][:128] + [0] * (seqlen - len(sample[x])) for sample in batch] # 0: <pad>

**Comment by rajae-Bens** [comment]
Hi,

Thank s for ur answer. The train function works now but it gave me an error in the conlleval.py file
when I read ur remarks in this file u said that it works for IOB2 or IOBES but I use only IOB in my data. 
Is it possible to adapt it for IOB ? or it requires a big change for it?

here is the error

![Screen Shot 2020-11-23 at 2 21 14 PM](https://user-images.githubusercontent.com/58187895/99966810-2b9db700-2d97-11eb-81e9-add491a8f18a.png)

**Comment by Dhanachandra** [comment]
Can you share me a sentence of your dataset in conll formal. And also check if your chunk tag (B-ENTITY) is spitted by underscore( _ ) if so, replaced it by hyphen( - ).

**Comment by rajae-Bens** [comment]
As I said before my dataset has the IOB scheme 
ex

Le O
restaurant B
se O
trouve O
en O
centre O
ville O

**Comment by Dhanachandra** [comment]
what is after B for the second token restaurant? If it is only B then make it something like B-TAG or B-ENTITY. 

Also check the line number 42 return chunk_tag.split('-', maxsplit=1) in Conlleval.py

**Comment by rajae-Bens** [comment]
Yes It worked, I am really grateful for ur help
 
another question plz 

How to predict one instance?

**Comment by Dhanachandra** [comment]
```
import spacy
import torch
spacy_tokenizer = spacy.load("en_core_web_sm", disable=["tagger", "parser", "ner"])
tokens = spacy_tokenizer(sentence) 
bert_tokens = np.array(['[CLS]'])
orig_to_tok_map = np.array([], dtype="i")
begins = np.array([], dtype="i")
ends = np.array([], dtype="i")
original_token = np.array([])
for tmp_tok in tokens:
    new_token = np.array(self.bert_tokenizer.tokenize(tmp_tok.text))
    original_token = np.append(original_token, new_token)
    orig_to_tok_map = np.append(orig_to_tok_map, bert_tokens.shape[0])
    bert_tokens = np.append(bert_tokens, new_token)
    offset = sentence.find(token, offset)
    begins = np.append(begins, offset)
    ends = np.append(ends, offset + len(token))
    offset += len(token)
bert_tokens = np.append(bert_tokens, '[SEP]')
tok_ids = bert_tokenizer.convert_tokens_to_ids(bert_tokens)
attn_mask = [1] * len(tok_ids))    
tok_ids = torch.LongTensor([tok_ids])   
attn_mask = torch.LongTensor([attn_mask])
token_ids, attn_mask, org_tok_map
inputs = {'input_ids': token_ids.to(device),
          'attn_masks' : attn_mask.to(device)
         }  
with torch.torch.no_grad():
    tag_seqs = model(**inputs)
for j, orig_tok_idx in enumerate(org_tok_map):
    print(token[i][j] + '\t')
    pred_tag = unique_labels[tag_seqs[0][orig_tok_idx]]
    if pred_tag == 'X':
        pred_tag = 'O'
    print(pred_tag + '\n')
```

**Comment by rajae-Bens** [comment]
Hi,

thank s for the code

But It gave me an error 

in this line:  offset = sentence.find(token, offset)

NameError: name 'token' is not defined

I also remarked that the variable **offset** was referenced before assignment

**Comment by Dhanachandra** [comment]
Replace all token by tmp_tok.text

**Comment by rajae-Bens** [comment]
ok but for the offset variable, it must be referenced first no?

**Comment by Dhanachandra** [comment]
Obviously. And I just shared you the idea how you can get the prediction for a single sentence. I actually didn't run and test the code.You must be able to solve those small errors.

**Comment by rajae-Bens** [comment]
ok thank s for ur help
